baseurl = "https://www.openhwgroup.org/"
DefaultContentLanguage = "en"
title = ""
theme = "eclipsefdn-hugo-solstice-theme"
metaDataFormat = "yaml"
#googleAnalytics = ""
disableKinds = ["taxonomyTerm"]
themesDir = "node_modules/"

[Params]
  google_tag_manager = "GTM-5WLCZXC"
  layout_style = "astro"
  description = "OpenHW Group is a not-for-profit, global organization driven by its members and individual contributors where hardware and software designers collaborate on open source cores, related IP, tools and software projects."
  subtitle = ""
  seo_title_suffix = " | OpenHW Group"
  keywords = ["open-source", "risc-v", "hardware", "software", "hw", "sw", "eclipse ide"]
  logo = "images/openhw-landscape.png"
  styles = "css/styles.css"
  favicon = "images/favicon.ico"
# share_img = ""
  gcse = ""
# subtheme = ""
  header_wrapper_class = "header-default-bg-img"
  js = "js/solstice.js"
  featured_content_publish_target = "openhwgroup"
  call_for_action_text = "Download"
  call_for_action_url = "#"
  call_for_action_icon = ""
  jumbotron_class = "col-sm-20 col-sm-offset-2"

[taxonomies]
  category = "categories"
  tag = "tags"

[Author]
  name = "OpenHW Group"
  website = "https://www.openhwgroup.org"
  email = "info@openhwgroup.org"
# facebook = ""
  twitter = "openhwgroup"
# youtube = ""
# googleplus = ""
# linkedin = ""

[permalinks]
  news = "/:sections/:year/:month/:day/:slug/"

[blackfriday]
  plainIDAnchors = true
  hrefTargetBlank = true

[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 1

[[menu.main]]
  name = "Membership"
  url = "/membership/"
  weight = 2

[[menu.main]]
  name = "Projects"
  url = "/projects/"
  weight = 3

[[menu.main]]
  name = "Get Involved"
  url = "/get-involved/"
  weight = 4

[[menu.main]]
  name = "Resources"
  url = "/resources/"
  weight = 5
